### ISSUE TITLE
Solaris fix

### ISSUE THREAD

**Issue by Tagar** [Tagar/rman#3]
"The script doesn't even work on Solaris, as it hardcodes ORATAB to /etc/oratab. In Solaris, the location is not /etc/oratab"

**Comment by kranskydog** [comment]
In rman_backup_vars.sh

#set some global platform-dependent variables
ORATAB="/etc/oratab"
case `uname` in
	Linux)	HOSTNAME=`hostname -s`
			CVLIB='/opt/simpana/Base/libobk.so'			#Commvault library location
			;;
	AIX)	HOSTNAME=`hostname -s`
			CVLIB='/opt/simpana/Base64/libobk.a(shr.o)'
			;;
	HP-UX)	HOSTNAME=`hostname`
			CVLIB='/opt/simpana/Base64/libobk.sl'
			;;
	SunOS)	HOSTNAME=`hostname`
			CVLIB='/opt/simpana/Base64/libobk.so'
                        ORATAB="/var/opt/oracle/oratab"
			;;
esac

**Comment by Tagar** [comment]
@kranskydog thanks for the suggestion. 
If you could create a pull request with this change, I will be glad to accept this improvement.
I am not actively maintaining these scripts now.

**Comment by Tagar** [comment]
thank you @kranskydog 
resolved with https://github.com/Tagar/rman/commit/2bc528b89bec14ddce4dbafb0d9c574cae8d8a11
